---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook: #for local tests use dt_webhook as source
        host: localhost
        port: 1234
        token: '{{ var_eda_token }}' 

  rules:
    - name: API Endpoint not available
      condition: event.payload.eventData["event.name"] is match ("Monitoring not available")
      action:
        run_playbook:
          name: playbooks/run-task.yml   
