---
- name: Local event-driven-ansible test
  hosts: localhost
  tasks:
    - name: Print Dynatrace event
      ansible.builtin.debug:
        msg: "{{ ansible_eda.event.payload }}"
    - name: "Here could be your ansible task for resolving the problem"
      ansible.builtin.debug:
        msg: "Resolve problem for the following affected entities {{ ansible_eda.event.payload.eventData.affected_entity_ids }}"
